name: Continous Integration

on:
  push:
    branches: 
      - main

  workflow_dispatch:
  
env: 
  DOTNET_VERSION: '6.0.x'
  AZURE_WEBAPP_NAME: test-github-action-workflow
  AZURE_WEBAPP_PACKAGE_PATH: '.'
    
jobs:
  build:
    runs-on: windows-latest
    steps: 
      - name: checkout the code
        uses: actions/checkout@v3

      - name: setup dotnet 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: restore
        run: dotnet restore

      - name: build app
        run: dotnet build -c Release --no-restore

      - name: publish app
        run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy the app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}                                                                                                                                                                                       `` }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

    